Homework-5
js-tasks-ru/vue-20230320_irina-nic-yu pull request #5
Opened 2023-04-06 16:18 UTC by irinanic88

2023-04-06 16:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-08 14:05 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-04-10 23:26 UTC, ShGKme requested changes
Разделение на компоненты в `04-vue-cli/02-TheToaster` получилось не очень удачным. Предлагается посмотреть, как сделать новые компоненты более самостоятельными и переиспользуемыми, а также более удобными для пользователя компонентов.

2023-04-10 23:26 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Оборачивание в скобки () тут лишнее. Это необходимо только в стрелочных функциях, где `{}` означали бы блок кода, а не объект.

2023-04-10 23:26 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
На мой взгляд такие объекты с привязкой классов лучше оставлять в шаблоне, чтобы сразу видеть вёрстку компонента.

2023-04-10 23:26 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Тернарный оператор принято использовать именно для вычисления значения в выражении, когда его возвращаемое значение далее используется в вычислении или присваивается (так как это именно оператор). Здесь же он используется для простого условия и выполнения действия. Для обычного ветвления лучше использовать классический if/else.

2023-04-10 23:26 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/CalendarDay.vue
> +}
Компонент `CalendarDay`, который и по названию и по реализации занимается выводом одной ячейки календаря, получает на вход все-все митапы для всех месяцев. Возможно, лучше заранее вычислить, какие митапы к каким дням относятся, и потом в один день передавать митапы только одного этого дня.

2023-04-10 23:26 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +</style>
Этот компонент совсем не является самостоятельным. Его нельзя использовать для вывода одного тоста, так как он выводит только внутренность тоста без контейнера и стилей тоста.

2023-04-10 23:26 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +    }
Обычно параметры удобнее передавать отдельно, не оборачивая их в ещё один объект. Параметры (пропсы) фактически уже объект ($props).

Передача отдельных параметров удобнее пользователю компонента: видны отдельные параметры и их типы без дополнительной документации и TypeScript, не нужно обязательно оборачивать в объект.

```html
<UiToast :toast="{ icon: 'error', message: 'error' }" />
<UiToast icon="error" message="error" />
```

2023-04-10 23:26 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/ToastsList.vue
> +</script>
Назначение этого компонента тоже не до конца ясно. Он выводит список тостов, но блок непосредственно всего списка `.toasts` и его стили остались в родительском компоненте.

2023-04-10 23:26 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      },
`availableToasts` - не данные компонента, не его реактивное и изменяемое состояние, а просто константа. Константу можно описать как обычную переменную в JS.

2023-04-10 23:26 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/ToastsList.vue
> +</script>
Для использования этого компонента пользователь компонента должен знать, что передать надо именно массив объектов, где в объектах описание тостов, включая классы для стилизации разных типов тостов. Это очень неудобный интерфейс компонента - пользователь компонента должен не просто знать, что бывают тосты успеха или ошибок, а знать конкретные имена классов из внутренней реализации этого компонента (`toast_success`).

2023-04-11 16:27 UTC, irinanic88 commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Исправлено

2023-04-11 16:28 UTC, irinanic88 commented on 04-vue-cli/04-MeetupsCalendar/components/CalendarDay.vue
> +}
Были сомнения на этот счет. Спасибо, исправила

2023-04-11 16:28 UTC, irinanic88 commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +    }
Исправлено

2023-04-11 16:32 UTC, irinanic88 commented on 04-vue-cli/02-TheToaster/components/ToastsList.vue
> +</script>
Понимаю комментарий. Но не понимаю тогда что может делать этот компонент, описанный в задании: "Дополнительно можно сделать глупый компонент для всего списка тостов, не занимающийся управлением тостами." Поэтому пока просто удалила его

2023-04-11 16:32 UTC, irinanic88 commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      },
Исправлено

2023-04-12 18:43 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/ToastsList.vue
> +</script>
Компонент списка тостов может принимать на вход массив тостов и выводить блок со всеми тостами в фиксированном блоке (в `<div class="toasts">`). В этом случае он уже выводит весь список одним блоком именно в виде очереди тостов на странице, и его дополнительная работа - выводить тосты именно как список, включая стилизацию этого блока.

В прокомментированном решении компонент работает как `v-for` для `UiToast` после переноса вёрстки тоста в компонент тоста.

2023-04-12 20:13 UTC, ShGKme approved these changes
Принято, но обратите внимание на комментарий по `04-vue-cli/04-MeetupsCalendar`. Это место можно будет поправить в новой итерации решения задачи в будущей теме, где календарь будет реализовываться вновь в более универсальном виде.

2023-04-12 20:13 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +      />
Вызывать методы в шаблоне в целом не лучшая практика во Vue, где шаблоны стараются держать декларативными и простыми. Это допустимо для форматирования вывода и маленьких утилитных функций, которые производительны и не имеют побочных эффектов. Рендеринг шаблона должен быть быстрым.

Но этот метод - это метод обработки данных, получающий данные для вывода в конкретном месте. Такой реализации лучше избегать, готовя данные заранее. Например, можно вызывать этот метод ещё при вычислении `calendarsItems` и сохранять результат сразу в данные ячейки. Либо вычислять какую-то структуру данных, которая позволяет сразу получить митапы определённого дня.

2023-04-12 20:14 UTC, merged